import type { CapitalSource, ExecutionPath, PriorityAlert, PriorityAlertLeg } from "./types";

const GBP_PER_USD = 0.7874;

const AUTO_POOLS: PriorityAlert["autoPools"] = [
  { venue: "polymarket", currency: "USD", autoPoolNative: 100 },
  { venue: "matchbook", currency: "GBP", autoPoolNative: 100 },
  { venue: "smarkets", currency: "GBP", autoPoolNative: 100 },
];

function leg(
  partial: Omit<PriorityAlertLeg, "capitalSource" | "executionPath"> & {
    capitalSource?: CapitalSource;
    executionPath?: ExecutionPath;
  },
): PriorityAlertLeg {
  return {
    capitalSource: partial.capitalSource ?? "AUTO_POOL",
    executionPath: partial.executionPath ?? "PAPER_INTERNAL",
    ...partial,
  };
}

export const PRIORITY_ALERT_FIXTURES: PriorityAlert[] = [
  {
    alertId: "pa-ncl-ars-2026-04-12-mr",
    opportunityId: "opp-ncl-ars-mr-001",
    severity: "CRITICAL",
    openedAt: "2026-04-12T14:02:18.180Z",
    event: {
      canonicalEventId: "evt-ncl-ars-2026-04-12",
      competition: "Premier League",
      homeTeam: "Newcastle United",
      awayTeam: "Arsenal",
      kickoffUtc: "2026-04-12T15:30:00.000Z",
    },
    market: {
      canonicalMarketId: "mkt-ncl-ars-mr-reg",
      family: "match_result",
      label: "Match result",
      period: "full_time",
      settlement: "Regulation time (90 minutes + stoppage)",
      settlementKey: "regulation_time",
    },
    netGuaranteedEdge: 0.098,
    expectedProfitGbpAtRecommended: 46.55,
    expectedRoiAtRecommended: 0.0482,
    recommendedSizeGbp: 475,
    rawLimitingDepthGbp: 500,
    safetyHaircut: 0.05,
    maxValidatedSizeGbp: 475,
    maxTheoreticalSizeGbp: 500,
    limitingLegId: "leg-smarkets-home",
    quoteAgeMs: 180,
    fillConfidence: "HIGH",
    fillConfidenceScore: 0.91,
    fillConfidenceFactors: [
      { id: "depth", label: "Depth coverage", value: "95%", note: "Recommended size uses 475 of £500 visible limiting depth", supportive: true },
      { id: "freshness", label: "Quote freshness", value: "180ms", note: "All required legs inside the 400ms freshness gate", supportive: true },
      { id: "persistence", label: "Quote persistence", value: "14s", note: "Top of book held through three consecutive snapshots", supportive: true },
      { id: "levels", label: "Book levels required", value: "1", note: "Limiting stake fills at the displayed top level", supportive: true },
      { id: "latency", label: "Latency assumption", value: "80ms", note: "Paper round-trip assumption, not a live fill clock", supportive: true },
      { id: "paper-fill", label: "Historical paper fills", value: "91%", note: "Illustrative fixture rate until Agent AB contracts land", supportive: true },
    ],
    executionRiskScore: 18,
    executionRiskBand: "low",
    gbpPerUsd: GBP_PER_USD,
    whyExceptional: "9.8% net guaranteed edge after costs with £500 limiting-leg depth. Polymarket away is MANUAL_EXTERNAL and must not draw AUTO_POOL.",
    dataSource: "DEMO_FIXTURE",
    paperMode: true,
    executionPath: "MANUAL_EXTERNAL",
    operatorLifecycle: "AWAITING_EXTERNAL_LEG_CONFIRMATION",
    autoPools: AUTO_POOLS,
    legs: [
      leg({
        legId: "leg-smarkets-home",
        venue: "smarkets",
        currency: "GBP",
        outcome: "home",
        selectionLabel: "Newcastle",
        decimalOdds: 2.133,
        visibleDepthNative: 500,
        visibleDepthGbp: 500,
        quoteAgeMs: 180,
        bookLevelsRequired: 1,
        isLimiting: true,
        recommendedStakeNative: 475,
        recommendedStakeGbp: 475,
        capitalSource: "MANUAL_OVERRIDE",
      }),
      leg({
        legId: "leg-matchbook-draw",
        venue: "matchbook",
        currency: "GBP",
        outcome: "draw",
        selectionLabel: "Draw",
        decimalOdds: 4.5,
        visibleDepthNative: 5000,
        visibleDepthGbp: 5000,
        quoteAgeMs: 160,
        bookLevelsRequired: 1,
        isLimiting: false,
        recommendedStakeNative: 225.15,
        recommendedStakeGbp: 225.15,
        capitalSource: "MANUAL_OVERRIDE",
      }),
      leg({
        legId: "leg-polymarket-away",
        venue: "polymarket",
        currency: "USD",
        outcome: "away",
        selectionLabel: "Arsenal",
        decimalOdds: 3.8,
        visibleDepthNative: 8000,
        visibleDepthGbp: 6299.2,
        quoteAgeMs: 210,
        bookLevelsRequired: 2,
        isLimiting: false,
        recommendedStakeNative: 338.54,
        recommendedStakeGbp: 266.59,
        capitalSource: "MANUAL_EXTERNAL",
        executionPath: "MANUAL_EXTERNAL",
      }),
    ],
  },
  {
    alertId: "pa-val-sev-2026-04-12-ou25",
    opportunityId: "opp-val-sev-ou25-002",
    severity: "HIGH_PRIORITY",
    openedAt: "2026-04-12T13:44:02.000Z",
    event: {
      canonicalEventId: "evt-val-sev-2026-04-12",
      competition: "La Liga",
      homeTeam: "Valencia",
      awayTeam: "Sevilla",
      kickoffUtc: "2026-04-12T17:00:00.000Z",
    },
    market: {
      canonicalMarketId: "mkt-val-sev-ou25",
      family: "total_goals",
      label: "Over 2.5 goals",
      period: "full_time",
      settlement: "Regulation time totals",
      settlementKey: "regulation_time",
    },
    netGuaranteedEdge: 0.041,
    expectedProfitGbpAtRecommended: 12.18,
    expectedRoiAtRecommended: 0.031,
    recommendedSizeGbp: 297,
    rawLimitingDepthGbp: 320,
    safetyHaircut: 0.05,
    maxValidatedSizeGbp: 304,
    maxTheoreticalSizeGbp: 320,
    limitingLegId: "leg-matchbook-over",
    quoteAgeMs: 240,
    fillConfidence: "HIGH",
    fillConfidenceScore: 0.84,
    fillConfidenceFactors: [
      { id: "depth", label: "Depth coverage", value: "93%", note: "Recommended size inside haircuted Matchbook over depth", supportive: true },
      { id: "freshness", label: "Quote freshness", value: "240ms", note: "Inside the 400ms gate", supportive: true },
      { id: "persistence", label: "Quote persistence", value: "8s", note: "Held across two snapshots", supportive: true },
      { id: "levels", label: "Book levels required", value: "2", note: "Second level required on Polymarket under", supportive: false },
      { id: "latency", label: "Latency assumption", value: "95ms", note: "Paper assumption only", supportive: true },
      { id: "paper-fill", label: "Historical paper fills", value: "86%", note: "Fixture until live paper stats exist", supportive: true },
    ],
    executionRiskScore: 27,
    executionRiskBand: "low",
    gbpPerUsd: GBP_PER_USD,
    whyExceptional: "Positive net edge after costs with both legs still inside standing freshness and depth gates.",
    dataSource: "DEMO_FIXTURE",
    paperMode: true,
    executionPath: "PAPER_INTERNAL",
    operatorLifecycle: "OPEN",
    autoPools: AUTO_POOLS,
    legs: [
      leg({
        legId: "leg-matchbook-over",
        venue: "matchbook",
        currency: "GBP",
        outcome: "over",
        selectionLabel: "Over 2.5",
        decimalOdds: 1.92,
        visibleDepthNative: 320,
        visibleDepthGbp: 320,
        quoteAgeMs: 240,
        bookLevelsRequired: 1,
        isLimiting: true,
        recommendedStakeNative: 297,
        recommendedStakeGbp: 297,
        capitalSource: "MANUAL_OVERRIDE",
      }),
      leg({
        legId: "leg-polymarket-under",
        venue: "polymarket",
        currency: "USD",
        outcome: "under",
        selectionLabel: "Under 2.5",
        decimalOdds: 2.18,
        visibleDepthNative: 2100,
        visibleDepthGbp: 2519.68,
        quoteAgeMs: 190,
        bookLevelsRequired: 2,
        isLimiting: false,
        recommendedStakeNative: 119.18,
        recommendedStakeGbp: 93.84,
        capitalSource: "MANUAL_OVERRIDE",
      }),
    ],
  },
  {
    alertId: "pa-int-nap-2026-04-12-btts",
    opportunityId: "opp-int-nap-btts-003",
    severity: "PRIORITY",
    openedAt: "2026-04-12T13:21:40.000Z",
    event: {
      canonicalEventId: "evt-int-nap-2026-04-12",
      competition: "Serie A",
      homeTeam: "Inter",
      awayTeam: "Napoli",
      kickoffUtc: "2026-04-12T19:45:00.000Z",
    },
    market: {
      canonicalMarketId: "mkt-int-nap-btts",
      family: "both_teams_to_score",
      label: "Both teams to score",
      period: "full_time",
      settlement: "Regulation time",
      settlementKey: "regulation_time",
    },
    netGuaranteedEdge: 0.027,
    expectedProfitGbpAtRecommended: 6.46,
    expectedRoiAtRecommended: 0.022,
    recommendedSizeGbp: 239,
    rawLimitingDepthGbp: 260,
    safetyHaircut: 0.05,
    maxValidatedSizeGbp: 247,
    maxTheoreticalSizeGbp: 260,
    limitingLegId: "leg-smarkets-yes",
    quoteAgeMs: 310,
    fillConfidence: "MEDIUM",
    fillConfidenceScore: 0.72,
    fillConfidenceFactors: [
      { id: "depth", label: "Depth coverage", value: "92%", note: "Smarkets yes is the limiting book", supportive: true },
      { id: "freshness", label: "Quote freshness", value: "310ms", note: "Still inside the freshness gate", supportive: true },
      { id: "persistence", label: "Quote persistence", value: "5s", note: "Shorter hold than the CRITICAL fixture", supportive: false },
      { id: "levels", label: "Book levels required", value: "1", note: "Top-of-book fill on both legs", supportive: true },
      { id: "latency", label: "Latency assumption", value: "110ms", note: "Paper assumption only", supportive: true },
      { id: "paper-fill", label: "Historical paper fills", value: "74%", note: "Fixture until Agent AB contracts land", supportive: false },
    ],
    executionRiskScore: 34,
    executionRiskBand: "moderate",
    gbpPerUsd: GBP_PER_USD,
    whyExceptional: "Cleared ordinary arb checks with enough expected profit to escalate, but weaker persistence than CRITICAL.",
    dataSource: "DEMO_FIXTURE",
    paperMode: true,
    executionPath: "PAPER_INTERNAL",
    operatorLifecycle: "OPEN",
    autoPools: AUTO_POOLS,
    legs: [
      leg({
        legId: "leg-smarkets-yes",
        venue: "smarkets",
        currency: "GBP",
        outcome: "yes",
        selectionLabel: "Yes",
        decimalOdds: 1.74,
        visibleDepthNative: 260,
        visibleDepthGbp: 260,
        quoteAgeMs: 310,
        bookLevelsRequired: 1,
        isLimiting: true,
        recommendedStakeNative: 239,
        recommendedStakeGbp: 239,
      }),
      leg({
        legId: "leg-matchbook-no",
        venue: "matchbook",
        currency: "GBP",
        outcome: "no",
        selectionLabel: "No",
        decimalOdds: 2.21,
        visibleDepthNative: 1800,
        visibleDepthGbp: 1800,
        quoteAgeMs: 280,
        bookLevelsRequired: 1,
        isLimiting: false,
        recommendedStakeNative: 54.72,
        recommendedStakeGbp: 54.72,
      }),
    ],
  },
];
