"""LEGACY import path for registered settlement-assumption helpers.

New code should import ``sports_hedge.matching.assumed_settlement``.
This module remains so existing tests and callers keep resolving.
"""

from sports_hedge.matching.assumed_settlement import (
    BTTS_OUTCOMES,
    FAIR_PRICE_PAPER_ADMITTED_REASON,
    FTTS_OUTCOMES,
    LEGACY_NOT_LIVE_EXECUTION_REASONS,
    LOCKED_PAPER_FAMILIES,
    OWNER_APPROVED_PAPER_EQUIVALENCE_REASON,
    PAPER_ASSUMED_AUDIT_REASONS,
    PAPER_ASSUMED_REASON,
    PAPER_NONBLOCKING_REJECTION_REASONS,
    REGISTERED_EQUIVALENT_SETTLEMENT_NOTE,
    TOTAL_OUTCOMES,
    allow_unknown_settlement_for_paper_assumed,
    both_independently_proven_regulation,
    has_complete_locked_outcomes,
    is_locked_paper_family,
    is_safe_half_line_total,
    kalshi_has_proven_settlement_contradiction,
    matchbook_regulation_convention,
    pair_structural_identity_matches,
    paper_assumed_locked_family,
    paper_assumed_match_reasons,
    paper_assumed_solver_model,
    required_outcomes_for_family,
    runner_outcomes,
    structural_locked_identity,
)

__all__ = [
    "BTTS_OUTCOMES",
    "FAIR_PRICE_PAPER_ADMITTED_REASON",
    "FTTS_OUTCOMES",
    "LEGACY_NOT_LIVE_EXECUTION_REASONS",
    "LOCKED_PAPER_FAMILIES",
    "OWNER_APPROVED_PAPER_EQUIVALENCE_REASON",
    "PAPER_ASSUMED_AUDIT_REASONS",
    "PAPER_ASSUMED_REASON",
    "PAPER_NONBLOCKING_REJECTION_REASONS",
    "REGISTERED_EQUIVALENT_SETTLEMENT_NOTE",
    "TOTAL_OUTCOMES",
    "allow_unknown_settlement_for_paper_assumed",
    "both_independently_proven_regulation",
    "has_complete_locked_outcomes",
    "is_locked_paper_family",
    "is_safe_half_line_total",
    "kalshi_has_proven_settlement_contradiction",
    "matchbook_regulation_convention",
    "pair_structural_identity_matches",
    "paper_assumed_locked_family",
    "paper_assumed_match_reasons",
    "paper_assumed_solver_model",
    "required_outcomes_for_family",
    "runner_outcomes",
    "structural_locked_identity",
]
